/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as PolicyImport } from './routes/policy'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppAuthImport } from './routes/_app/_auth'
import { Route as AppLoginLayoutImport } from './routes/_app/login/_layout'
import { Route as AppLoginLayoutIndexImport } from './routes/_app/login/_layout.index'
import { Route as AppAuthStoriesLayoutImport } from './routes/_app/_auth/stories/_layout'
import { Route as AppAuthOnboardingLayoutImport } from './routes/_app/_auth/onboarding/_layout'
import { Route as AppAuthGenerateLayoutImport } from './routes/_app/_auth/generate/_layout'
import { Route as AppAuthDashboardLayoutImport } from './routes/_app/_auth/dashboard/_layout'
import { Route as AppAuthStoriesLayoutIndexImport } from './routes/_app/_auth/stories/_layout.index'
import { Route as AppAuthGenerateLayoutIndexImport } from './routes/_app/_auth/generate/_layout.index'
import { Route as AppAuthDashboardLayoutIndexImport } from './routes/_app/_auth/dashboard/_layout.index'
import { Route as AppAuthStoriesLayoutStoryIdImport } from './routes/_app/_auth/stories/_layout.$storyId'
import { Route as AppAuthOnboardingLayoutUsernameImport } from './routes/_app/_auth/onboarding/_layout.username'
import { Route as AppAuthDashboardLayoutSettingsImport } from './routes/_app/_auth/dashboard/_layout.settings'
import { Route as AppAuthDashboardLayoutCheckoutImport } from './routes/_app/_auth/dashboard/_layout.checkout'
import { Route as AppAuthStoriesLayoutStoryIdIndexImport } from './routes/_app/_auth/stories/_layout.$storyId.index'
import { Route as AppAuthDashboardLayoutSettingsIndexImport } from './routes/_app/_auth/dashboard/_layout.settings.index'
import { Route as AppAuthStoriesLayoutStoryIdRefineImport } from './routes/_app/_auth/stories/_layout.$storyId.refine'
import { Route as AppAuthDashboardLayoutSettingsBillingImport } from './routes/_app/_auth/dashboard/_layout.settings.billing'

// Create Virtual Routes

const AppLoginImport = createFileRoute('/_app/login')()
const AppAuthStoriesImport = createFileRoute('/_app/_auth/stories')()
const AppAuthOnboardingImport = createFileRoute('/_app/_auth/onboarding')()
const AppAuthGenerateImport = createFileRoute('/_app/_auth/generate')()
const AppAuthDashboardImport = createFileRoute('/_app/_auth/dashboard')()

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const PolicyRoute = PolicyImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLoginRoute = AppLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthRoute = AppAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthStoriesRoute = AppAuthStoriesImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthOnboardingRoute = AppAuthOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthGenerateRoute = AppAuthGenerateImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppAuthDashboardRoute = AppAuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAuthRoute,
} as any)

const AppLoginLayoutRoute = AppLoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppLoginRoute,
} as any)

const AppLoginLayoutIndexRoute = AppLoginLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLoginLayoutRoute,
} as any)

const AppAuthStoriesLayoutRoute = AppAuthStoriesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthStoriesRoute,
} as any)

const AppAuthOnboardingLayoutRoute = AppAuthOnboardingLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthOnboardingRoute,
} as any)

const AppAuthGenerateLayoutRoute = AppAuthGenerateLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthGenerateRoute,
} as any)

const AppAuthDashboardLayoutRoute = AppAuthDashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppAuthDashboardRoute,
} as any)

const AppAuthStoriesLayoutIndexRoute = AppAuthStoriesLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthStoriesLayoutRoute,
} as any)

const AppAuthGenerateLayoutIndexRoute = AppAuthGenerateLayoutIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthGenerateLayoutRoute,
  } as any,
)

const AppAuthDashboardLayoutIndexRoute =
  AppAuthDashboardLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthStoriesLayoutStoryIdRoute =
  AppAuthStoriesLayoutStoryIdImport.update({
    id: '/$storyId',
    path: '/$storyId',
    getParentRoute: () => AppAuthStoriesLayoutRoute,
  } as any)

const AppAuthOnboardingLayoutUsernameRoute =
  AppAuthOnboardingLayoutUsernameImport.update({
    id: '/username',
    path: '/username',
    getParentRoute: () => AppAuthOnboardingLayoutRoute,
  } as any)

const AppAuthDashboardLayoutSettingsRoute =
  AppAuthDashboardLayoutSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthDashboardLayoutCheckoutRoute =
  AppAuthDashboardLayoutCheckoutImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AppAuthDashboardLayoutRoute,
  } as any)

const AppAuthStoriesLayoutStoryIdIndexRoute =
  AppAuthStoriesLayoutStoryIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthStoriesLayoutStoryIdRoute,
  } as any)

const AppAuthDashboardLayoutSettingsIndexRoute =
  AppAuthDashboardLayoutSettingsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

const AppAuthStoriesLayoutStoryIdRefineRoute =
  AppAuthStoriesLayoutStoryIdRefineImport.update({
    id: '/refine',
    path: '/refine',
    getParentRoute: () => AppAuthStoriesLayoutStoryIdRoute,
  } as any)

const AppAuthDashboardLayoutSettingsBillingRoute =
  AppAuthDashboardLayoutSettingsBillingImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppAuthDashboardLayoutSettingsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/_app/_auth': {
      id: '/_app/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthImport
      parentRoute: typeof AppImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginImport
      parentRoute: typeof AppImport
    }
    '/_app/login/_layout': {
      id: '/_app/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginLayoutImport
      parentRoute: typeof AppLoginRoute
    }
    '/_app/_auth/dashboard': {
      id: '/_app/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/dashboard/_layout': {
      id: '/_app/_auth/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthDashboardLayoutImport
      parentRoute: typeof AppAuthDashboardRoute
    }
    '/_app/_auth/generate': {
      id: '/_app/_auth/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppAuthGenerateImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/generate/_layout': {
      id: '/_app/_auth/generate/_layout'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppAuthGenerateLayoutImport
      parentRoute: typeof AppAuthGenerateRoute
    }
    '/_app/_auth/onboarding': {
      id: '/_app/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/onboarding/_layout': {
      id: '/_app/_auth/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppAuthOnboardingLayoutImport
      parentRoute: typeof AppAuthOnboardingRoute
    }
    '/_app/_auth/stories': {
      id: '/_app/_auth/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AppAuthStoriesImport
      parentRoute: typeof AppAuthImport
    }
    '/_app/_auth/stories/_layout': {
      id: '/_app/_auth/stories/_layout'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AppAuthStoriesLayoutImport
      parentRoute: typeof AppAuthStoriesRoute
    }
    '/_app/login/_layout/': {
      id: '/_app/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof AppLoginLayoutIndexImport
      parentRoute: typeof AppLoginLayoutImport
    }
    '/_app/_auth/dashboard/_layout/checkout': {
      id: '/_app/_auth/dashboard/_layout/checkout'
      path: '/checkout'
      fullPath: '/dashboard/checkout'
      preLoaderRoute: typeof AppAuthDashboardLayoutCheckoutImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings': {
      id: '/_app/_auth/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/onboarding/_layout/username': {
      id: '/_app/_auth/onboarding/_layout/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof AppAuthOnboardingLayoutUsernameImport
      parentRoute: typeof AppAuthOnboardingLayoutImport
    }
    '/_app/_auth/stories/_layout/$storyId': {
      id: '/_app/_auth/stories/_layout/$storyId'
      path: '/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof AppAuthStoriesLayoutStoryIdImport
      parentRoute: typeof AppAuthStoriesLayoutImport
    }
    '/_app/_auth/dashboard/_layout/': {
      id: '/_app/_auth/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppAuthDashboardLayoutIndexImport
      parentRoute: typeof AppAuthDashboardLayoutImport
    }
    '/_app/_auth/generate/_layout/': {
      id: '/_app/_auth/generate/_layout/'
      path: '/'
      fullPath: '/generate/'
      preLoaderRoute: typeof AppAuthGenerateLayoutIndexImport
      parentRoute: typeof AppAuthGenerateLayoutImport
    }
    '/_app/_auth/stories/_layout/': {
      id: '/_app/_auth/stories/_layout/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof AppAuthStoriesLayoutIndexImport
      parentRoute: typeof AppAuthStoriesLayoutImport
    }
    '/_app/_auth/dashboard/_layout/settings/billing': {
      id: '/_app/_auth/dashboard/_layout/settings/billing'
      path: '/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsBillingImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/stories/_layout/$storyId/refine': {
      id: '/_app/_auth/stories/_layout/$storyId/refine'
      path: '/refine'
      fullPath: '/stories/$storyId/refine'
      preLoaderRoute: typeof AppAuthStoriesLayoutStoryIdRefineImport
      parentRoute: typeof AppAuthStoriesLayoutStoryIdImport
    }
    '/_app/_auth/dashboard/_layout/settings/': {
      id: '/_app/_auth/dashboard/_layout/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof AppAuthDashboardLayoutSettingsIndexImport
      parentRoute: typeof AppAuthDashboardLayoutSettingsImport
    }
    '/_app/_auth/stories/_layout/$storyId/': {
      id: '/_app/_auth/stories/_layout/$storyId/'
      path: '/'
      fullPath: '/stories/$storyId/'
      preLoaderRoute: typeof AppAuthStoriesLayoutStoryIdIndexImport
      parentRoute: typeof AppAuthStoriesLayoutStoryIdImport
    }
  }
}

// Create and export the route tree

interface AppAuthDashboardLayoutSettingsRouteChildren {
  AppAuthDashboardLayoutSettingsBillingRoute: typeof AppAuthDashboardLayoutSettingsBillingRoute
  AppAuthDashboardLayoutSettingsIndexRoute: typeof AppAuthDashboardLayoutSettingsIndexRoute
}

const AppAuthDashboardLayoutSettingsRouteChildren: AppAuthDashboardLayoutSettingsRouteChildren =
  {
    AppAuthDashboardLayoutSettingsBillingRoute:
      AppAuthDashboardLayoutSettingsBillingRoute,
    AppAuthDashboardLayoutSettingsIndexRoute:
      AppAuthDashboardLayoutSettingsIndexRoute,
  }

const AppAuthDashboardLayoutSettingsRouteWithChildren =
  AppAuthDashboardLayoutSettingsRoute._addFileChildren(
    AppAuthDashboardLayoutSettingsRouteChildren,
  )

interface AppAuthDashboardLayoutRouteChildren {
  AppAuthDashboardLayoutCheckoutRoute: typeof AppAuthDashboardLayoutCheckoutRoute
  AppAuthDashboardLayoutSettingsRoute: typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  AppAuthDashboardLayoutIndexRoute: typeof AppAuthDashboardLayoutIndexRoute
}

const AppAuthDashboardLayoutRouteChildren: AppAuthDashboardLayoutRouteChildren =
  {
    AppAuthDashboardLayoutCheckoutRoute: AppAuthDashboardLayoutCheckoutRoute,
    AppAuthDashboardLayoutSettingsRoute:
      AppAuthDashboardLayoutSettingsRouteWithChildren,
    AppAuthDashboardLayoutIndexRoute: AppAuthDashboardLayoutIndexRoute,
  }

const AppAuthDashboardLayoutRouteWithChildren =
  AppAuthDashboardLayoutRoute._addFileChildren(
    AppAuthDashboardLayoutRouteChildren,
  )

interface AppAuthDashboardRouteChildren {
  AppAuthDashboardLayoutRoute: typeof AppAuthDashboardLayoutRouteWithChildren
}

const AppAuthDashboardRouteChildren: AppAuthDashboardRouteChildren = {
  AppAuthDashboardLayoutRoute: AppAuthDashboardLayoutRouteWithChildren,
}

const AppAuthDashboardRouteWithChildren =
  AppAuthDashboardRoute._addFileChildren(AppAuthDashboardRouteChildren)

interface AppAuthGenerateLayoutRouteChildren {
  AppAuthGenerateLayoutIndexRoute: typeof AppAuthGenerateLayoutIndexRoute
}

const AppAuthGenerateLayoutRouteChildren: AppAuthGenerateLayoutRouteChildren = {
  AppAuthGenerateLayoutIndexRoute: AppAuthGenerateLayoutIndexRoute,
}

const AppAuthGenerateLayoutRouteWithChildren =
  AppAuthGenerateLayoutRoute._addFileChildren(
    AppAuthGenerateLayoutRouteChildren,
  )

interface AppAuthGenerateRouteChildren {
  AppAuthGenerateLayoutRoute: typeof AppAuthGenerateLayoutRouteWithChildren
}

const AppAuthGenerateRouteChildren: AppAuthGenerateRouteChildren = {
  AppAuthGenerateLayoutRoute: AppAuthGenerateLayoutRouteWithChildren,
}

const AppAuthGenerateRouteWithChildren = AppAuthGenerateRoute._addFileChildren(
  AppAuthGenerateRouteChildren,
)

interface AppAuthOnboardingLayoutRouteChildren {
  AppAuthOnboardingLayoutUsernameRoute: typeof AppAuthOnboardingLayoutUsernameRoute
}

const AppAuthOnboardingLayoutRouteChildren: AppAuthOnboardingLayoutRouteChildren =
  {
    AppAuthOnboardingLayoutUsernameRoute: AppAuthOnboardingLayoutUsernameRoute,
  }

const AppAuthOnboardingLayoutRouteWithChildren =
  AppAuthOnboardingLayoutRoute._addFileChildren(
    AppAuthOnboardingLayoutRouteChildren,
  )

interface AppAuthOnboardingRouteChildren {
  AppAuthOnboardingLayoutRoute: typeof AppAuthOnboardingLayoutRouteWithChildren
}

const AppAuthOnboardingRouteChildren: AppAuthOnboardingRouteChildren = {
  AppAuthOnboardingLayoutRoute: AppAuthOnboardingLayoutRouteWithChildren,
}

const AppAuthOnboardingRouteWithChildren =
  AppAuthOnboardingRoute._addFileChildren(AppAuthOnboardingRouteChildren)

interface AppAuthStoriesLayoutStoryIdRouteChildren {
  AppAuthStoriesLayoutStoryIdRefineRoute: typeof AppAuthStoriesLayoutStoryIdRefineRoute
  AppAuthStoriesLayoutStoryIdIndexRoute: typeof AppAuthStoriesLayoutStoryIdIndexRoute
}

const AppAuthStoriesLayoutStoryIdRouteChildren: AppAuthStoriesLayoutStoryIdRouteChildren =
  {
    AppAuthStoriesLayoutStoryIdRefineRoute:
      AppAuthStoriesLayoutStoryIdRefineRoute,
    AppAuthStoriesLayoutStoryIdIndexRoute:
      AppAuthStoriesLayoutStoryIdIndexRoute,
  }

const AppAuthStoriesLayoutStoryIdRouteWithChildren =
  AppAuthStoriesLayoutStoryIdRoute._addFileChildren(
    AppAuthStoriesLayoutStoryIdRouteChildren,
  )

interface AppAuthStoriesLayoutRouteChildren {
  AppAuthStoriesLayoutStoryIdRoute: typeof AppAuthStoriesLayoutStoryIdRouteWithChildren
  AppAuthStoriesLayoutIndexRoute: typeof AppAuthStoriesLayoutIndexRoute
}

const AppAuthStoriesLayoutRouteChildren: AppAuthStoriesLayoutRouteChildren = {
  AppAuthStoriesLayoutStoryIdRoute:
    AppAuthStoriesLayoutStoryIdRouteWithChildren,
  AppAuthStoriesLayoutIndexRoute: AppAuthStoriesLayoutIndexRoute,
}

const AppAuthStoriesLayoutRouteWithChildren =
  AppAuthStoriesLayoutRoute._addFileChildren(AppAuthStoriesLayoutRouteChildren)

interface AppAuthStoriesRouteChildren {
  AppAuthStoriesLayoutRoute: typeof AppAuthStoriesLayoutRouteWithChildren
}

const AppAuthStoriesRouteChildren: AppAuthStoriesRouteChildren = {
  AppAuthStoriesLayoutRoute: AppAuthStoriesLayoutRouteWithChildren,
}

const AppAuthStoriesRouteWithChildren = AppAuthStoriesRoute._addFileChildren(
  AppAuthStoriesRouteChildren,
)

interface AppAuthRouteChildren {
  AppAuthDashboardRoute: typeof AppAuthDashboardRouteWithChildren
  AppAuthGenerateRoute: typeof AppAuthGenerateRouteWithChildren
  AppAuthOnboardingRoute: typeof AppAuthOnboardingRouteWithChildren
  AppAuthStoriesRoute: typeof AppAuthStoriesRouteWithChildren
}

const AppAuthRouteChildren: AppAuthRouteChildren = {
  AppAuthDashboardRoute: AppAuthDashboardRouteWithChildren,
  AppAuthGenerateRoute: AppAuthGenerateRouteWithChildren,
  AppAuthOnboardingRoute: AppAuthOnboardingRouteWithChildren,
  AppAuthStoriesRoute: AppAuthStoriesRouteWithChildren,
}

const AppAuthRouteWithChildren =
  AppAuthRoute._addFileChildren(AppAuthRouteChildren)

interface AppLoginLayoutRouteChildren {
  AppLoginLayoutIndexRoute: typeof AppLoginLayoutIndexRoute
}

const AppLoginLayoutRouteChildren: AppLoginLayoutRouteChildren = {
  AppLoginLayoutIndexRoute: AppLoginLayoutIndexRoute,
}

const AppLoginLayoutRouteWithChildren = AppLoginLayoutRoute._addFileChildren(
  AppLoginLayoutRouteChildren,
)

interface AppLoginRouteChildren {
  AppLoginLayoutRoute: typeof AppLoginLayoutRouteWithChildren
}

const AppLoginRouteChildren: AppLoginRouteChildren = {
  AppLoginLayoutRoute: AppLoginLayoutRouteWithChildren,
}

const AppLoginRouteWithChildren = AppLoginRoute._addFileChildren(
  AppLoginRouteChildren,
)

interface AppRouteChildren {
  AppAuthRoute: typeof AppAuthRouteWithChildren
  AppLoginRoute: typeof AppLoginRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthRoute: AppAuthRouteWithChildren,
  AppLoginRoute: AppLoginRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppAuthRouteWithChildren
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/login': typeof AppLoginLayoutRouteWithChildren
  '/dashboard': typeof AppAuthDashboardLayoutRouteWithChildren
  '/generate': typeof AppAuthGenerateLayoutRouteWithChildren
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/stories': typeof AppAuthStoriesLayoutRouteWithChildren
  '/login/': typeof AppLoginLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/stories/$storyId': typeof AppAuthStoriesLayoutStoryIdRouteWithChildren
  '/dashboard/': typeof AppAuthDashboardLayoutIndexRoute
  '/generate/': typeof AppAuthGenerateLayoutIndexRoute
  '/stories/': typeof AppAuthStoriesLayoutIndexRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/stories/$storyId/refine': typeof AppAuthStoriesLayoutStoryIdRefineRoute
  '/dashboard/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/stories/$storyId/': typeof AppAuthStoriesLayoutStoryIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppAuthRouteWithChildren
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/login': typeof AppLoginLayoutIndexRoute
  '/dashboard': typeof AppAuthDashboardLayoutIndexRoute
  '/generate': typeof AppAuthGenerateLayoutIndexRoute
  '/onboarding': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/stories': typeof AppAuthStoriesLayoutIndexRoute
  '/dashboard/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/onboarding/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/dashboard/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/stories/$storyId/refine': typeof AppAuthStoriesLayoutStoryIdRefineRoute
  '/dashboard/settings': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/stories/$storyId': typeof AppAuthStoriesLayoutStoryIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/_app/_auth': typeof AppAuthRouteWithChildren
  '/_app/login': typeof AppLoginRouteWithChildren
  '/_app/login/_layout': typeof AppLoginLayoutRouteWithChildren
  '/_app/_auth/dashboard': typeof AppAuthDashboardRouteWithChildren
  '/_app/_auth/dashboard/_layout': typeof AppAuthDashboardLayoutRouteWithChildren
  '/_app/_auth/generate': typeof AppAuthGenerateRouteWithChildren
  '/_app/_auth/generate/_layout': typeof AppAuthGenerateLayoutRouteWithChildren
  '/_app/_auth/onboarding': typeof AppAuthOnboardingRouteWithChildren
  '/_app/_auth/onboarding/_layout': typeof AppAuthOnboardingLayoutRouteWithChildren
  '/_app/_auth/stories': typeof AppAuthStoriesRouteWithChildren
  '/_app/_auth/stories/_layout': typeof AppAuthStoriesLayoutRouteWithChildren
  '/_app/login/_layout/': typeof AppLoginLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/checkout': typeof AppAuthDashboardLayoutCheckoutRoute
  '/_app/_auth/dashboard/_layout/settings': typeof AppAuthDashboardLayoutSettingsRouteWithChildren
  '/_app/_auth/onboarding/_layout/username': typeof AppAuthOnboardingLayoutUsernameRoute
  '/_app/_auth/stories/_layout/$storyId': typeof AppAuthStoriesLayoutStoryIdRouteWithChildren
  '/_app/_auth/dashboard/_layout/': typeof AppAuthDashboardLayoutIndexRoute
  '/_app/_auth/generate/_layout/': typeof AppAuthGenerateLayoutIndexRoute
  '/_app/_auth/stories/_layout/': typeof AppAuthStoriesLayoutIndexRoute
  '/_app/_auth/dashboard/_layout/settings/billing': typeof AppAuthDashboardLayoutSettingsBillingRoute
  '/_app/_auth/stories/_layout/$storyId/refine': typeof AppAuthStoriesLayoutStoryIdRefineRoute
  '/_app/_auth/dashboard/_layout/settings/': typeof AppAuthDashboardLayoutSettingsIndexRoute
  '/_app/_auth/stories/_layout/$storyId/': typeof AppAuthStoriesLayoutStoryIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/policy'
    | '/terms'
    | '/login'
    | '/dashboard'
    | '/generate'
    | '/onboarding'
    | '/stories'
    | '/login/'
    | '/dashboard/checkout'
    | '/dashboard/settings'
    | '/onboarding/username'
    | '/stories/$storyId'
    | '/dashboard/'
    | '/generate/'
    | '/stories/'
    | '/dashboard/settings/billing'
    | '/stories/$storyId/refine'
    | '/dashboard/settings/'
    | '/stories/$storyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/policy'
    | '/terms'
    | '/login'
    | '/dashboard'
    | '/generate'
    | '/onboarding'
    | '/stories'
    | '/dashboard/checkout'
    | '/onboarding/username'
    | '/dashboard/settings/billing'
    | '/stories/$storyId/refine'
    | '/dashboard/settings'
    | '/stories/$storyId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/policy'
    | '/terms'
    | '/_app/_auth'
    | '/_app/login'
    | '/_app/login/_layout'
    | '/_app/_auth/dashboard'
    | '/_app/_auth/dashboard/_layout'
    | '/_app/_auth/generate'
    | '/_app/_auth/generate/_layout'
    | '/_app/_auth/onboarding'
    | '/_app/_auth/onboarding/_layout'
    | '/_app/_auth/stories'
    | '/_app/_auth/stories/_layout'
    | '/_app/login/_layout/'
    | '/_app/_auth/dashboard/_layout/checkout'
    | '/_app/_auth/dashboard/_layout/settings'
    | '/_app/_auth/onboarding/_layout/username'
    | '/_app/_auth/stories/_layout/$storyId'
    | '/_app/_auth/dashboard/_layout/'
    | '/_app/_auth/generate/_layout/'
    | '/_app/_auth/stories/_layout/'
    | '/_app/_auth/dashboard/_layout/settings/billing'
    | '/_app/_auth/stories/_layout/$storyId/refine'
    | '/_app/_auth/dashboard/_layout/settings/'
    | '/_app/_auth/stories/_layout/$storyId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PolicyRoute: typeof PolicyRoute
  TermsRoute: typeof TermsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PolicyRoute: PolicyRoute,
  TermsRoute: TermsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/policy",
        "/terms"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_auth",
        "/_app/login"
      ]
    },
    "/policy": {
      "filePath": "policy.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/_app/_auth": {
      "filePath": "_app/_auth.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_auth/dashboard",
        "/_app/_auth/generate",
        "/_app/_auth/onboarding",
        "/_app/_auth/stories"
      ]
    },
    "/_app/login": {
      "filePath": "_app/login",
      "parent": "/_app",
      "children": [
        "/_app/login/_layout"
      ]
    },
    "/_app/login/_layout": {
      "filePath": "_app/login/_layout.tsx",
      "parent": "/_app/login",
      "children": [
        "/_app/login/_layout/"
      ]
    },
    "/_app/_auth/dashboard": {
      "filePath": "_app/_auth/dashboard",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/dashboard/_layout"
      ]
    },
    "/_app/_auth/dashboard/_layout": {
      "filePath": "_app/_auth/dashboard/_layout.tsx",
      "parent": "/_app/_auth/dashboard",
      "children": [
        "/_app/_auth/dashboard/_layout/checkout",
        "/_app/_auth/dashboard/_layout/settings",
        "/_app/_auth/dashboard/_layout/"
      ]
    },
    "/_app/_auth/generate": {
      "filePath": "_app/_auth/generate",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/generate/_layout"
      ]
    },
    "/_app/_auth/generate/_layout": {
      "filePath": "_app/_auth/generate/_layout.tsx",
      "parent": "/_app/_auth/generate",
      "children": [
        "/_app/_auth/generate/_layout/"
      ]
    },
    "/_app/_auth/onboarding": {
      "filePath": "_app/_auth/onboarding",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/onboarding/_layout"
      ]
    },
    "/_app/_auth/onboarding/_layout": {
      "filePath": "_app/_auth/onboarding/_layout.tsx",
      "parent": "/_app/_auth/onboarding",
      "children": [
        "/_app/_auth/onboarding/_layout/username"
      ]
    },
    "/_app/_auth/stories": {
      "filePath": "_app/_auth/stories",
      "parent": "/_app/_auth",
      "children": [
        "/_app/_auth/stories/_layout"
      ]
    },
    "/_app/_auth/stories/_layout": {
      "filePath": "_app/_auth/stories/_layout.tsx",
      "parent": "/_app/_auth/stories",
      "children": [
        "/_app/_auth/stories/_layout/$storyId",
        "/_app/_auth/stories/_layout/"
      ]
    },
    "/_app/login/_layout/": {
      "filePath": "_app/login/_layout.index.tsx",
      "parent": "/_app/login/_layout"
    },
    "/_app/_auth/dashboard/_layout/checkout": {
      "filePath": "_app/_auth/dashboard/_layout.checkout.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings": {
      "filePath": "_app/_auth/dashboard/_layout.settings.tsx",
      "parent": "/_app/_auth/dashboard/_layout",
      "children": [
        "/_app/_auth/dashboard/_layout/settings/billing",
        "/_app/_auth/dashboard/_layout/settings/"
      ]
    },
    "/_app/_auth/onboarding/_layout/username": {
      "filePath": "_app/_auth/onboarding/_layout.username.tsx",
      "parent": "/_app/_auth/onboarding/_layout"
    },
    "/_app/_auth/stories/_layout/$storyId": {
      "filePath": "_app/_auth/stories/_layout.$storyId.tsx",
      "parent": "/_app/_auth/stories/_layout",
      "children": [
        "/_app/_auth/stories/_layout/$storyId/refine",
        "/_app/_auth/stories/_layout/$storyId/"
      ]
    },
    "/_app/_auth/dashboard/_layout/": {
      "filePath": "_app/_auth/dashboard/_layout.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout"
    },
    "/_app/_auth/generate/_layout/": {
      "filePath": "_app/_auth/generate/_layout.index.tsx",
      "parent": "/_app/_auth/generate/_layout"
    },
    "/_app/_auth/stories/_layout/": {
      "filePath": "_app/_auth/stories/_layout.index.tsx",
      "parent": "/_app/_auth/stories/_layout"
    },
    "/_app/_auth/dashboard/_layout/settings/billing": {
      "filePath": "_app/_auth/dashboard/_layout.settings.billing.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/stories/_layout/$storyId/refine": {
      "filePath": "_app/_auth/stories/_layout.$storyId.refine.tsx",
      "parent": "/_app/_auth/stories/_layout/$storyId"
    },
    "/_app/_auth/dashboard/_layout/settings/": {
      "filePath": "_app/_auth/dashboard/_layout.settings.index.tsx",
      "parent": "/_app/_auth/dashboard/_layout/settings"
    },
    "/_app/_auth/stories/_layout/$storyId/": {
      "filePath": "_app/_auth/stories/_layout.$storyId.index.tsx",
      "parent": "/_app/_auth/stories/_layout/$storyId"
    }
  }
}
ROUTE_MANIFEST_END */
